spring.datasource.url=jdbc:mysql://localhost:3306/localshop_cashback?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Sandip@7489



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
spring.application.name=cashback
